name: '${name}'
version: '${version}'
main: '${main}'
description: 'RSPlugin - ${name}'
api-version: '${api_version}'
folia-supported: true
depend: [ RSFramework, packetevents ]
softdepend: [ ]
authors: [ '${author}' ]